              
name: Coveralls GitHub Action
uses: coverallsapp/github-action@v2.3.4
on: 
  push:
    paths-ignore:
      - '../../src/.internal/**'
      - '../../src/test/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      # Set up environment
      - name: Set up Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      # Install dependencies
      - name: Install dependencies
        run: |
            npm install
            npm test
        continue-on-error: true

      # Upload coverage
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}