name: CI Pipeline
on: 
  push:
    paths:
      - 'src/**'
    paths-ignore:
      - '/.internal/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      # Set up environment
      - name: Set up Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      # Install dependencies
      - name: Install dependencies
        run: |
            npm install
            npm test
        continue-on-error: true