# Trigger the workflow on push or pull request
on: ["push", "pull_request"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
            npm install
            npm test -- --coverage

      # Step 5: Upload coverage to Coveralls
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}