# Trigger the workflow on push or pull request
on: ["push", "pull_request"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
            npm install
            npm test -- --coverage
        continue-on-error: true

      # Step4: Check if coverage file exists and conditionally upload to Coveralls
      - name: Check for coverage file
        id: check_coverage
        run: |
          if [ -f coverage/lcov-info ]; then
            echo "Coverage file found, proceeding with upload."
          else
            echo "No coverage file found, skipping Coveralls upload."
            exit 0  # Exit gracefully if no coverage file is found
          fi

      # Step 5: Upload coverage to Coveralls
      - name: Coveralls
        if: steps.check_coverage.outcome == 'success'
        uses: coverallsapp/github-action@v2
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}